project:
  type: website

website:
  page-navigation: true
  title: "WGFAST 2025"
  description: "Homepage ICES WGFAST meeting at Hafr√≥/MFRI in 2025"
  site-url: "https://wgfast.hafro.is/"

  repo-url: "https://github.com/sigurdurthorjonsson/wgfast2025"
#  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    left: "This page is built with [Quarto](https://quarto.org/)."
    right: "![](images/logos/hafro.png){width=25%}"
    background: "#4A90E2" # Updated to match palette (light blue)ht blue)

  sidebar:
    background: "#4A90E2" # Updated to match palette (dark blue)dark blue)
    logo: "images/Sine_waves_different_frequencies.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sigurdurthorjonsson/wgfast2025
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: practical-info.qmd
       text: Practical Information
     - href: program.qmd
       text: Agenda
     - href: excursion.qmd
       text: Excursion
     - href: https://wgfast.hafro.is/#our-sponsors
       text: Our Sponsors

format:
  html:
    theme:
      light: [cosmo, style/theme.scss]
      dark: [cosmo, style/theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible" # Highly readable font
    highlight-style: a11y # Accessible syntax highlighting
    self-contained: false

editor: visual
